City game
BuTaMuH4er/mybot_study pull request #1
Opened 2021-02-28 18:56 UTC by BuTaMuH4er

2021-03-02 14:59 UTC, alexandrettio requested changes

2021-03-02 14:59 UTC, alexandrettio commented on bot.py
> +    date_full_moon = update.message.text.split('/next_full_moon ')[1]
Тут лучше делать не сплит, а слайс 
date_full_moon = update.message.text[15:]

2021-03-02 14:59 UTC, alexandrettio commented on game_citys.py
> +def city_game(update, context):
Не очень понятное название функции :(

2021-03-02 14:59 UTC, alexandrettio commented on game_citys.py
> +        letter = city[-1]
Тут могут быть сложные моменты с "ъ"/"ь"

2021-03-02 14:59 UTC, alexandrettio commented on game_citys.py
> +        letter = city[-1]
Ага вижу закомментированную функцию выше...

2021-03-02 14:59 UTC, alexandrettio commented on game_citys.py
> +    #Ответ бота, на нужную букву рандомно ищем город и возвращаем его
Ох.. тут тяжело. Тут ты можешь долго выбирать. Проблема в том как ты хранишь города. Я бы предложаила переписать на словарь вида
cities: {
'a': ['архангельск', 'арзамас', ...],
'б': ['бобруйск', ...]
}

Иначе в этом месте у тебя программа может зависнуть если города на нужную букву нет

2021-03-02 14:59 UTC, alexandrettio commented on game_citys.py
> +    list_citys.remove(city)
А за счет чего list_cities обновляется? Сейчас бот как-то работает? Или не работает никак?

2021-03-03 10:41 UTC, closed without merging

2021-03-03 10:42 UTC, BuTaMuH4er commented
Внесены поправки в бота.